[package]
name = "euler"
version = "0.1.0"
authors = ["Stephen Haywood <stephen@averagesecurityguy.info>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.4.3"
primes = "0.3.0"
